version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NANOBANANA_URL=https://api.nanobanana.ai/v1/inpaint
      - NANOBANANA_KEY=demo_key_placeholder
      - REQUEST_TIMEOUT=120
      - DEBUG=True
      - LOG_LEVEL=INFO
      - ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
