name: Frontend Quality Gates

on:
  push:
    branches: [ main ]
    paths: ['frontend/**']
  pull_request:
    branches: [ main ]
    paths: ['frontend/**']

jobs:
  lighthouse:
    name: Lighthouse Performance & Accessibility
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Build application
      working-directory: ./frontend
      run: npm run build
    
    - name: Start preview server
      working-directory: ./frontend
      run: npm run preview --port 4173 &
    
    - name: Wait for server
      run: timeout 30 bash -c 'until curl -f http://localhost:4173; do sleep 1; done'
    
    - name: Run Lighthouse CI
      working-directory: ./frontend
      run: |
        npm install -g @lhci/cli@0.12.x
        lhci autorun --config=.lighthouserc.json
    
    - name: Upload Lighthouse results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lighthouse-results
        path: frontend/lighthouse-results/

  axe-accessibility:
    name: Axe Accessibility Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./frontend
      run: |
        npm ci
        npm install -D @axe-core/cli
    
    - name: Build application
      working-directory: ./frontend
      run: npm run build
    
    - name: Start preview server
      working-directory: ./frontend
      run: npm run preview --port 4173 &
    
    - name: Wait for server
      run: timeout 30 bash -c 'until curl -f http://localhost:4173; do sleep 1; done'
    
    - name: Run axe accessibility tests
      working-directory: ./frontend
      run: |
        npx axe http://localhost:4173 \
          --exit \
          --tags wcag2a,wcag2aa,wcag21aa \
          --reporter junit \
          --save axe-results.xml
    
    - name: Upload axe results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: axe-results
        path: frontend/axe-results.xml
